apiVersion: apps/v1
kind: Deployment
metadata:
  name: config
  labels:
    app: config
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: config
    spec:
      containers:
      - image: jmc22071983/config-services:0.0.2-SNAPSHOT
        name: config
        ports:
        - containerPort: 8888