apiVersion: apps/v1 # Usa apps/v1beta2 para versiones anteriores a 1.9.0
kind: Deployment
metadata:
  name: config-deployment
spec:
  selector:
    matchLabels:
      app: config
  replicas: 1 # indica al controlador que ejecute 2 pods
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: config
        image: jmc22071983/config-services:0.0.2-SNAPSHOT
        ports:
        - containerPort: 8888