apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-service
  labels:
    app: hotels-service
spec:
  selector:
    matchLabels:
      app: hotels-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hotels-service
    spec:
      containers:
      - image: jmc22071983/hotels-service-k8s:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: hotels-service
        env:
        - name: COUCHBASE_ADDR
          value: http://couchbase:8091
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        ports:
        - containerPort: 8073