apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-breweries-deploy
  labels:
    app: hotel-breweries-deploy
spec:
  selector:
    matchLabels:
      app: hotel-breweries-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hotel-breweries-service
    spec:
      containers:
      - image: jmc22071983/hotel-breweries-service-k8s:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: hotel-breweries-service
        env:
        - name: COUCHBASE_ADDR
          value: http://couchbase:8091
        - name: SPRING_PROFILES_ACTIVE
          value: k8s
        ports:
        - containerPort: 8074