apiVersion: apps/v1
kind: Deployment
metadata:
  name: breweries-deploy
  labels:
    app: breweries-deploy
spec:
  selector:
    matchLabels:
      app: breweries-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: breweries-service
    spec:
      containers:
      - image: jmc22071983/breweries-service-k8s:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: breweries-service
        envFrom:
        - configMapRef:
            name: config-map
---

apiVersion: v1
kind: Service
metadata:
  name: breweries-service
spec:
  selector:
    app: breweries-service
  ports:
    - port: 8072
      targetPort: 8072
  type: ClusterIP