apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels-deploy
  labels:
    app: hotels-deploy
spec:
  selector:
    matchLabels:
      app: hotels-service
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hotels-service
    spec:
      containers:
      - image: jmc22071983/hotels-service-k8s:0.0.1-SNAPSHOT
        imagePullPolicy: Always
        name: hotels-service
        envFrom:
        - configMapRef:
            name: config-map
---

apiVersion: v1
kind: Service
metadata:
  name: hotels-service
spec:
  selector:
    app: hotels-service
  ports:
    - port: 8073
      targetPort: 8073
  type: ClusterIP